# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

#
# Created: 18th August 2025
# Updated: 3rd September 2025
#

name: Go

env:
  VERBOSITY: 1

on:
  push:
    branches: [ "master", "dev", "gha" ]
  pull_request:
    branches: [ "master", "dev", "gha" ]

jobs:

  build:
    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        go-version:
        - '1.24'
        - '1.23'
        - '1.22'
        - '1.21'
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4

    - name: "Set up Go ${{matrix.go-version}}"
      uses: actions/setup-go@v4
      with:
        go-version: '${{matrix.go-version}}'

    - name: "Display Go version"
      run: go version

    - name: "Build all targets"
      run: ./build.sh

    - name: "Run all unit-tests"
      run: ./run_all_unit_tests.sh --verbosity ${{env.VERBOSITY}}
